### ISSUE TITLE
Problem with change password

### ISSUE THREAD

**Issue by ghost** [CTUIR/CDMS#17]
I found a CDMS error.  Friday,  I had forgotten my password so I dug up the masquerade password and logged in  as Admin and changed my password and saved it.  Then I logged out and tried to get back in in my own account.  Surprize – the new password didn’t work.  Did it all one more time and still didn’t work.  So it looks like we have found a bug.  

Colleen Roe

**Comment by kenburcham** [comment]
I can't reproduce this. Are you guys using the Active Directory SSO? It should work in either case and seems to work for me. :/

**Comment by kenburcham** [comment]
I just tried this again and it works fine. Can you please provide steps to reproduce? I'll re-open if it is still an issue.
