### ISSUE TITLE
Header fields in Detail grid (possible bug)

### ISSUE THREAD

**Issue by cwatry** [CTUIR/CDMS#21]
We noticed there are Header fields that are also being displayed in the Detail grid.  Specifically, the Location, Activity Date, and QA Status fields are unnecessarily replicated in the grid.

**Comment by kenburcham** [comment]
Are they being displayed in BOTH places? Or are header fields being displayed as detail fields?
Can you post a screenshot and also your dataset config (config column of your dataset in question).

**Comment by cwatry** [comment]
Both places.  I believe this is the same thing Ryan just sent an email out about.

[cid:image001.png@01D449C5.D624FC00]

**Comment by kenburcham** [comment]
Yesterday we discovered that this was due to some hardcoding in the datasheet.js, fixed in the next commit.
