### ISSUE TITLE
Field Properties panel in the Administration tools needs implement a scroll bar

### ISSUE THREAD

**Issue by Coinerc** [CTUIR/CDMS#6]
On the Field Properties in side of the Administration of a dataset the window needs to not expand past the limit of the window.

The panel needs to has a scroll bar if it the panel is longer than the current window.  Because it is sticky it currently won't allow you to get to the save or remove button or other objects if the window is too long.
![capture](https://user-images.githubusercontent.com/10835895/41879238-4ec04bfc-78c8-11e8-95c9-035605e2f06b.JPG)

**Comment by kenburcham** [comment]
completed
